3.0.0
cordova-plugin-facebook-connect/cordova-plugin-facebook-connect pull request #60
Opened 2021-04-08 02:05 UTC by noahcooper

2021-08-14 22:27 UTC, xriter requested changes
There are two bugs in _facebook-native.js_ 

1: in `exports.setApplicationId` the called function should be `setApplicationId` (now it states `getApplicationId`.

2: in `exports.setApplicationName` the called function should be `setApplicationName` (now it states `getApplicationName`.

2021-08-14 22:34 UTC, xriter requested changes

2021-08-14 22:34 UTC, xriter commented on www/facebook-native.js
> +  exec(s, f, 'FacebookConnectPlugin', 'getApplicationId', [appId])
```suggestion
  exec(s, f, 'FacebookConnectPlugin', 'setApplicationId', [appId])
```

2021-08-14 22:34 UTC, xriter commented on www/facebook-native.js
> +  exec(s, f, 'FacebookConnectPlugin', 'getApplicationName', [appName])
```suggestion
  exec(s, f, 'FacebookConnectPlugin', 'setApplicationName', [appName])
```

2021-08-14 22:44 UTC, xriter commented
Experienced during iOS testing:
When switching appID with `setApplicationId()` one might get an error saying that the url 'fbXXXXXXXXXXXXnull' doesn't exist in the CFBundleURLSchemes (where XXXXXXXX is the appID). These aren't added to the info.plist during plugin installation. Only for the original appID.

Maybe some documentation in the readme could state that one can resolve this, by adding something like the following lines to their config.xml:
`
<platform name="ios">
 <config-file parent="CFBundleURLTypes" target="*-Info.plist">
            <array>
                <dict>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>fbXXXXappID1XXXXnull</string>
                    </array>
                </dict>
                <dict>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>fbXXXXappID2XXXXnull</string>
                    </array>
                </dict>
                <dict>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>fbXXXXappID3XXXXnull</string>
                    </array>
                </dict>
            </array>
        </config-file>
</platform>
`

(Haven't tested this in Android yet).

2021-08-14 23:20 UTC, xriter commented
Getting the following error while building:
"
Thread 1: "As of v9.0, you must initialize the SDK prior to calling any methods or setting any properties. You can do this by calling `FBSDKApplicationDelegate`'s `application:didFinishLaunchingWithOptions:` method. Learn more: https://developers.facebook.com/docs/ios/getting-startedIf no `UIApplication` is available you can use `FBSDKApplicationDelegate`'s `initializeSDK` method."
"
(in main.m on line 32:
 `int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");`
)

Not sure what causes this or how to fix it.
The previous release doesn't have this problem.

2021-08-16 18:40 UTC, noahcooper commented
@xriter thanks for your feedback. This release is still a work in progress, but should be finalized tomorrow.

2021-08-17 03:52 UTC, merged